name: samadhan_saathi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_app_check: ^0.3.2
  cloud_firestore: ^5.6.7
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/logo/
    - assets/lottie/