name: samadhan_saathi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_app_check: ^0.3.2
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.7
  lottie: ^3.3.1
  image_picker: ^1.1.2
  http: ^1.4.0
  intl: ^0.19.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/logo/
    - assets/lottie/
    - assets/lang/